### ISSUE TITLE
Pass events to callback functions

### ISSUE THREAD

**Issue by ericcornelissen** [pushtell/keypress-combination#1]
I just started using this library and I really like it. However, I have one request/question. Is there a reason you're not passing on the event information from the original event listener:

``` javascript
30 |    window.addEventListener('keydown', function (e) {
```

To the callback functions registerd for a `KeypressCombinationEmitter` as following?

``` javascript
37 |    _this.listeners[key][i](/* shoudn't there be an 'e' here? */);
```

Btw, these snippets refer to [lib/index.js](https://github.com/pushtell/keypress-combination/blob/master/lib/index.js).

**Comment by wehriam** [comment]
Thanks! I appreciate you taking the time to provide feedback.

As the library uses combinations of events, we could hypothetically provide an array of the original events to the callback. As the earlier events are stale by the time the final key was pressed, this might be dangerous. 

Can you describe your use case for these events?

**Comment by ericcornelissen** [comment]
I hadn't considered the 'combination of events' thing at all since I figured the only applicable event is the last one, but I could be wrong...

My current use case is a keypress on the `enter` key when a HTML element with `contendetible=true` is focussed, it should prevent the default action (creating a new line) and do something else.

``` javascript
emitter.addListener(13 /* enter */, function(e) {
    e.preventDefault();
    // do stuff
});
```

**Comment by wehriam** [comment]
Not sure this library is necessary for that use case, could you do something like:

``` js
window.addEventListener('keydown', function(e) {
  if((e.keyCode ? e.keyCode : e.which) === 13) {
    e.preventDefault();
    // do stuff
  } 
});
```

**Comment by ericcornelissen** [comment]
Ow yea, that was kind of a bad example... You're right I could use that in the case of enter. But I do also have listeners for multiple keys, e.g. `ctrl`+`up` or `ctrl`+`down`.

**Comment by wehriam** [comment]
If a user were to press `ctrl` then `up`, the events would arrive separately and only trigger the `KeypressCombinationEmitter` callback after `up` was pressed - too late to cancel the `ctrl` event. 

Your best strategy is probably to listen for the key presses individually and prevent defaults on a case-by-case basis as necessary.

We could add a boolean `cancelAllEvents` option to the `KeypressCombinationEmitter`, but I think that would be confusing.

**Comment by ericcornelissen** [comment]
Isn't it always the case that the events arrive seperately and only the last key triggers the `KeypressCombinationEmitter` callback? Besides, in the case of my examples the problem lies in pressing either the `up` or `down` key, not the `ctrl` key (and the same goes for other examples, e.g. `ctrl`+`=` which will zoom-in in most browsers).

I would agree that adding such a boolean would be confusing, and I don't think it's a good idea. But could you elaborate on why you think giving the `event` variable of the last event isn't a good idea ?

**Comment by wehriam** [comment]
My only objection to passing the latest `event` variable is that it might also be confusing, as the `KeypressCombinationEmitter` is listening for sets of `keydown` and `keyup` events. It makes sense for the events to be more accessible though, let me see if I can come up with a good solution.

**Comment by ericcornelissen** [comment]
This is one solution I came up with, it enforces users of the library to think about using the events. When creating a `new KeypressCombinationEmitter` there is an optional parameter which can enable the returning of events.

``` javascript
25 |     function KeypressCombinationEmitter(lock) {
26 |       lock = lock || false;
...
37 |       _this.listeners[key][i](lock ? events : undefined);
```

Also, this is how I would structure the object with events that is returned (it's not that special, you probably would've come up with something similar).

``` javascript
events = {
  "ctrl": eventsMap[keycode("ctrl")],
  "up": eventsMap[keycode("up")]
};
```
